name: Dafoe Designs
favicon: null
layout_spectrum: 0.4356612083502114
typography_spectrum: 0.9782572565600276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#037d94'
    - '#e8e4c9'
    - '#010101'
    - '#211d1b'
    - '#6e6b5c'
  brandStrength: 0.7974719619378448
  lightness: 0.4437660272233188
  saturation: 0.9776341537944973
  rhythmicContrast: 0.36795946792699397
purpose: []
