name: Dafoe Designs
favicon: null
layout_spectrum: 0.95589
typography_spectrum: 0.52097
title: CUSTOM GREETING CARDS AND ORIGINAL HANDMADE ARTWORK
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7fff4'
    - '#037c94'
    - '#000100'
    - '#92a59f'
    - '#514c33'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.36795946792699397
purpose: []
