name: Dafoe Designs
favicon: null
layout_spectrum: 0.95589
typography_spectrum: 0.06111
title: CUSTOM GREETING CARDS AND ORIGINAL HANDMADE ARTWORK
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#007e92'
    - '#070707'
    - '#afafaf'
    - '#444444'
  brandStrength: 0.875
  lightness: 0.4437660272233188
  saturation: 0.9776341537944973
  rhythmicContrast: 0.36795946792699397
purpose: []
