typography_spectrum: 0.52097
color:
  brandColors:
    - '#d7fff4'
    - '#037c94'
    - '#000100'
    - '#92a59f'
    - '#514c33'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.36795946792699397
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.95589
analytics:
  google: null
  facebook: null
  twitter: null
name: Dafoe Designs
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: CUSTOM GREETING CARDS AND ORIGINAL HANDMADE ARTWORK
description: THE GRID SUCKS
purpose: []
